[package]
name = "t"
version = "0.1.0"
authors = ["Kenton Hamaluik <kenton@rehabtronics.com>"]

[dependencies]
clap = "~2.32"
todo-txt = "~1.2"
home = "~0.3"
serde = "~1.0"
serde_derive = "~1.0"
toml = "~0.4"
crossterm = "~0.4"
